#!/usr/bin/env bash
# config/profiles/openclaw/provision.sh — install the OpenClaw toolchain into the yard (run as root
# inside the yard by 10-provision-profile.sh; idempotent). Vars: NODE_VERSION, COREPACK_VERSION,
# PNPM_VERSION, DEV_USER, OPTIONAL_FEATURES, and the cache contract forwarded from profile.conf
# (PIP_CACHE_DIR, npm_config_cache, npm_config_store_dir, PLAYWRIGHT_BROWSERS_PATH) — persisted into
# L1 login shells so parallel agents share ONE store instead of per-user duplicates.
set -euo pipefail

NODE_VERSION="${NODE_VERSION:-24.15.0}"
COREPACK_VERSION="${COREPACK_VERSION:-0.31.0}"
PNPM_VERSION="${PNPM_VERSION:-11.2.2}"
DEV_USER="${DEV_USER:-dev}"
OPTIONAL_FEATURES="${OPTIONAL_FEATURES:-}"

export DEBIAN_FRONTEND=noninteractive

# 1. Node — pinned, from nodejs.org into /usr/local (shadows the distro node).
if [ "$(/usr/local/bin/node --version 2>/dev/null)" != "v${NODE_VERSION}" ]; then
  case "$(dpkg --print-architecture)" in
    amd64) na=x64 ;; arm64) na=arm64 ;; *) echo "unsupported arch" >&2; exit 1 ;;
  esac
  tmp="$(mktemp -d)"; base="node-v${NODE_VERSION}-linux-${na}"
  curl -fsSL "https://nodejs.org/dist/v${NODE_VERSION}/${base}.tar.xz" -o "$tmp/${base}.tar.xz"
  curl -fsSL "https://nodejs.org/dist/v${NODE_VERSION}/SHASUMS256.txt" -o "$tmp/sha.txt"
  ( cd "$tmp" && grep " ${base}.tar.xz\$" sha.txt | sha256sum -c - )
  # tar won't prune files a new release dropped, so an in-place major upgrade would merge the old
  # npm/corepack into the new one (broken deps, e.g. minipass mismatch). Replace them cleanly.
  rm -rf /usr/local/lib/node_modules/npm /usr/local/lib/node_modules/corepack
  tar -xJf "$tmp/${base}.tar.xz" -C /usr/local --strip-components=1
  rm -rf "$tmp"
fi

# 2. corepack + pnpm; arch-scoped shim so ad-hoc installs don't pull win/mac/musl native variants.
/usr/local/bin/npm install -g "corepack@${COREPACK_VERSION}" >/dev/null
/usr/local/bin/corepack enable >/dev/null
/usr/local/bin/corepack prepare "pnpm@${PNPM_VERSION}" --activate >/dev/null
cat > /usr/local/bin/pnpm <<'SH'
#!/usr/bin/env bash
# arch-scoped so ad-hoc installs don't pull win/mac/musl native variants. pnpm honors fetch-timeout
# only as a CLI flag (not .npmrc / npm_config_* env), and the yard's egress is slow on OpenClaw's huge
# native/ML tarballs → inject a generous one for install-type commands.
ft=; case "${1:-}" in install|add|update|up|i|fetch) ft="--fetch-timeout=1800000" ;; esac
exec corepack pnpm \
  --config.supportedArchitectures.os=linux \
  --config.supportedArchitectures.cpu=current \
  --config.supportedArchitectures.libc=glibc "$@" $ft
SH
chmod +x /usr/local/bin/pnpm

# 3. Python dev venv.
[ -x /opt/venv/bin/python ] || python3 -m venv /opt/venv
/opt/venv/bin/pip install -q --upgrade pip setuptools wheel

# 4. Shared caches (agents fill them; package managers point here via profile.conf).
install -d -o "$DEV_USER" -g "$DEV_USER" /srv/cache/pnpm /srv/cache/pip /srv/cache/npm

# 4b. Persist the shared-cache env so EVERY in-yard agent shares ONE /srv/cache store instead of
#     per-user duplicates (~/.npm, the default pnpm store, ~/.cache/pip → re-downloads, wasted disk).
#     profile.conf is the single source — its values reach us as env (forwarded as --env by
#     10-provision-profile.sh); we only re-emit them, never re-type the paths. TWO vehicles, because
#     agents enter L1 two ways and a login-only file would silently miss the common one:
#       /etc/profile.d/*.sh  — sourced by LOGIN shells (e.g. `su -`), like the android profile;
#       /etc/environment     — read by pam_env for ALL PAM sessions, so it ALSO reaches the
#                              non-login `yard ssh -- <cmd>` path (which sources neither profile.d
#                              nor ~/.bashrc). Plain KEY=VALUE, no `export`, no shell.
#     PLAYWRIGHT_* is emitted only when browser_tests is on (its cache dir is created only then).
browser_on=0
case " ${OPTIONAL_FEATURES:-} " in *" browser_tests "*) browser_on=1 ;; esac

{
  echo "# Subyard openclaw (L1) — share ONE /srv/cache store across parallel agents. GENERATED by"
  echo "# provision.sh from config/profiles/openclaw/profile.conf — do not edit; change the profile."
  [ -n "${PIP_CACHE_DIR:-}" ]        && echo "export PIP_CACHE_DIR=\"$PIP_CACHE_DIR\""
  [ -n "${npm_config_cache:-}" ]     && echo "export npm_config_cache=\"$npm_config_cache\""
  [ -n "${npm_config_store_dir:-}" ] && echo "export npm_config_store_dir=\"$npm_config_store_dir\""
  if [ "$browser_on" = 1 ] && [ -n "${PLAYWRIGHT_BROWSERS_PATH:-}" ]; then
    echo "export PLAYWRIGHT_BROWSERS_PATH=\"$PLAYWRIGHT_BROWSERS_PATH\""
    echo "export PLAYWRIGHT_SKIP_BROWSER_GC=1 # shared cache: never GC another agent's browser"
  fi
  echo "export SUBYARD_OPENCLAW_DOCS=/etc/subyard/openclaw-l1.md"
} > /etc/profile.d/subyard-openclaw-caches.sh
chmod 0644 /etc/profile.d/subyard-openclaw-caches.sh

# Same values for non-login PAM sessions. Idempotent: drop our marker block, never clobber other entries.
sed -i '/^# >>> subyard-openclaw >>>$/,/^# <<< subyard-openclaw <<<$/d' /etc/environment 2>/dev/null || true
{
  echo "# >>> subyard-openclaw >>>"
  [ -n "${PIP_CACHE_DIR:-}" ]        && echo "PIP_CACHE_DIR=$PIP_CACHE_DIR"
  [ -n "${npm_config_cache:-}" ]     && echo "npm_config_cache=$npm_config_cache"
  [ -n "${npm_config_store_dir:-}" ] && echo "npm_config_store_dir=$npm_config_store_dir"
  if [ "$browser_on" = 1 ] && [ -n "${PLAYWRIGHT_BROWSERS_PATH:-}" ]; then
    echo "PLAYWRIGHT_BROWSERS_PATH=$PLAYWRIGHT_BROWSERS_PATH"
    echo "PLAYWRIGHT_SKIP_BROWSER_GC=1"
  fi
  echo "SUBYARD_OPENCLAW_DOCS=/etc/subyard/openclaw-l1.md"
  echo "# <<< subyard-openclaw <<<"
} >> /etc/environment

# 5. OPTIONAL_FEATURES (off by default) — the heavy e2e capability.
for feat in $OPTIONAL_FEATURES; do
  case "$feat" in
    browser_tests)
      apt-get update -qq
      apt-get install -y -qq chromium fonts-liberation fonts-noto-color-emoji \
        libnss3 libgbm1 libxss1 libasound2t64 2>/dev/null \
        || apt-get install -y -qq chromium fonts-liberation libnss3 libgbm1
      install -d -o "$DEV_USER" -g "$DEV_USER" /srv/cache/playwright
      ;;
    sandbox_tests)
      # rootless docker — --force needed (rootful coexists); overlayfs is the native storage driver.
      apt-get update -qq
      apt-get install -y -qq docker-ce-rootless-extras fuse-overlayfs slirp4netns \
        bubblewrap dbus-user-session uidmap
      loginctl enable-linger "$DEV_USER" >/dev/null 2>&1 || true
      uid="$(id -u "$DEV_USER")"
      runuser -u "$DEV_USER" -- env XDG_RUNTIME_DIR="/run/user/$uid" \
        dockerd-rootless-setuptool.sh install --force >/dev/null 2>&1 || true
      # setup flips dev's default context to rootless — restore default so shared rootful project-env.sh works.
      runuser -u "$DEV_USER" -- env XDG_RUNTIME_DIR="/run/user/$uid" \
        docker context use default >/dev/null 2>&1 || true
      ;;
    *) echo "openclaw provision: unknown OPTIONAL_FEATURE '$feat' — skipping" >&2 ;;
  esac
done

# 6. Discoverable L1 how-to (self-serve onboarding): one persistent, machine/human-readable doc the
#    agent can find on its own. Pointer is exported as SUBYARD_OPENCLAW_DOCS (step 4b); the consumer
#    repo's AGENTS.md/CLAUDE.md should also point here (operator recommendation, we don't edit it).
#    Persistent /etc (NOT tmpfs /run/subyard): provision is operator-run once, not re-run on reboot.
install -d -m 0755 /etc/subyard
cat > /etc/subyard/openclaw-l1.md <<'DOC'
# OpenClaw in this yard — L1 build / test / live (self-serve)

You are in an **L1 yard**: several non-isolated agents share ONE machine and ONE set of caches.
BUILD and the unit suite run from your own checkout with no extra setup. The LIVE lane (a real model
move) is operator-gated — see below. There is no gateway and no Telegram in this lane.

Exact script names below follow the project's own `package.json`; confirm them with `pnpm run` if a
command is reported missing (the vendored project moves).

## Build
Run from your project workspace (the checkout you were given):

    pnpm install --frozen-lockfile      # uses the shared store; first run is slow on a cold cache
    pnpm build

## Test suite

    pnpm test:unit:fast                 # fast unit suite

The fuller matrices (e2e / docker-in-docker / browser / sandbox) need optional features and a
loopback gateway or docker socket that this plain L1 lane does not start. Run them only where the
operator enabled OPTIONAL_FEATURES (browser_tests / sandbox_tests) for this yard.

## Live model move, no gateway (operator-gated)

`sy-stage` appears on PATH ONLY after the operator runs `yard staging up <zone>` for a staging zone.
If it is absent, the live lane is not provisioned here yet — build and the unit suite still work.
When present:

    sy-stage test -- <your live-test command>          # e.g. OPENCLAW_LIVE_TEST=1 pnpm test:live

It runs your command in the staging runner (cwd /workspace) and injects the host-config STAGING
provider key as `ANTHROPIC_API_KEY` for THAT ONE subprocess only — never your shell env, never a log.
That injected key is what un-skips the project's key-gated live tests; with no key they skip cleanly.

- The project's own live suites gate on the provider key and on the project's own switch (e.g.
  `OPENCLAW_LIVE_TEST=1`, plus per-suite `OPENCLAW_LIVE_*` knobs) — pass those in your command. They
  do NOT read `SUBYARD_LIVE_MODEL`; that flag is only a Subyard convenience signal (set to 1 when a
  key is present) for your own wrappers to branch on, not a project contract.
- The key is host-config only; it is never in commits, logs, or your shell.

## Shared caches (you must understand this)

All agents in this yard share `/srv/cache` (pnpm store, npm, pip[, playwright]). The package-manager
env is preset for you (`PIP_CACHE_DIR` / `npm_config_cache` / `npm_config_store_dir`) in every shell,
login or `yard ssh -- <cmd>` — do NOT override the store/cache dirs per checkout, or you fork the
cache and re-download everything.

- Cache-mutating commands (`pnpm store prune`, `npm cache clean`, `pip cache purge`) are
  single-writer: never run them in parallel with another agent's build.
- pnpm hardlinks the store into `node_modules` only when `/srv/cache` and your workspace are on the
  same filesystem; otherwise it copies (slower, more disk) but still works. See profile.conf for the
  authoritative sharing rules.

## This lane does NOT
- start a gateway or connect Telegram (that is the staging/qa lane, operator-provisioned);
- give you any master credential — a live key, if present, is injected per-run and you never see it.
DOC
chmod 0644 /etc/subyard/openclaw-l1.md

echo "openclaw provision OK: node=$(/usr/local/bin/node --version) pnpm=$(/usr/local/bin/pnpm --version 2>/dev/null) venv=$([ -x /opt/venv/bin/python ] && echo yes)"
# Operator recommendation (Slice 3.2): the self-serve how-to is at /etc/subyard/openclaw-l1.md and is
# discoverable via $SUBYARD_OPENCLAW_DOCS. We do NOT edit the consumer's repo — hand this to them so an
# agent given only a prompt finds the lane. Printed here because that is where the operator will see it.
echo "openclaw provision: agent how-to at /etc/subyard/openclaw-l1.md (env: SUBYARD_OPENCLAW_DOCS)."
echo "  RECOMMEND adding to the project's AGENTS.md/CLAUDE.md:"
echo "    Building/testing in a Subyard L1 yard? Read \$SUBYARD_OPENCLAW_DOCS (/etc/subyard/openclaw-l1.md)."
